# Generated by Django 4.2.7 on 2023-11-12 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0005_delete_onetype_delete_threetype"),
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopproduct",
            name="product",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="product.product",
                verbose_name="商品",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shopproduct",
            name="shop",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="account.shop",
                verbose_name="店铺",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="shop",
            name="img_url",
            field=models.FileField(
                upload_to="static/account/images", verbose_name="图片地址"
            ),
        ),
    ]
