# Generated by Django 4.2.7 on 2023-11-13 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0005_delete_onetype_delete_threetype"),
        ("account", "0002_shopproduct_product_shopproduct_shop_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopproduct",
            name="account",
            field=models.ForeignKey(
                default=20,
                help_text="客户ID",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="shop",
            name="account",
            field=models.ForeignKey(
                help_text="客户ID",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="img_url",
            field=models.ImageField(
                help_text="店铺的封面",
                upload_to="static/account/images",
                verbose_name="图片地址",
            ),
        ),
        migrations.AlterField(
            model_name="shopproduct",
            name="product",
            field=models.ForeignKey(
                help_text="产品ID",
                on_delete=django.db.models.deletion.CASCADE,
                to="product.product",
                verbose_name="商品",
            ),
        ),
        migrations.AlterField(
            model_name="shopproduct",
            name="shop",
            field=models.ForeignKey(
                help_text="店铺ID",
                on_delete=django.db.models.deletion.CASCADE,
                to="account.shop",
                verbose_name="店铺",
            ),
        ),
    ]
