# Generated by Django 4.2.7 on 2023-11-13 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_shopproduct_account_alter_shop_account_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopproduct",
            name="account",
            field=models.ForeignKey(
                help_text="客户ID",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="客户",
            ),
        ),
    ]
