# Generated by Django 4.2.7 on 2023-11-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_shop_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='level',
            field=models.SmallIntegerField(choices=[(3, 'admin'), (2, 'editor'), (1, 'other')], default=1, help_text="角色/身份(3, 'admin'), (2, 'editor'), (1, 'other')", verbose_name='级别'),
        ),
    ]
