# Generated by Django 4.2.7 on 2023-11-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0007_rename_img_url_shop_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default=None,
                help_text="客户头像",
                null=True,
                upload_to="static/account/avatar/images",
                verbose_name="头像",
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="image",
            field=models.ImageField(
                help_text="店铺的封面",
                upload_to="static/account/shop/images",
                verbose_name="图片地址",
            ),
        ),
    ]
