# Generated by Django 4.2.7 on 2023-11-16 00:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0015_alter_product_cover_and_more"),
        ("account", "0008_account_avatar_alter_shop_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shop",
            name="account",
        ),
        migrations.RemoveField(
            model_name="shopproduct",
            name="account",
        ),
        migrations.RemoveField(
            model_name="shopproduct",
            name="product",
        ),
        migrations.RemoveField(
            model_name="shopproduct",
            name="shop",
        ),
        migrations.AddField(
            model_name="shop",
            name="account_id",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="客户ID",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="shopproduct",
            name="account_id",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="客户ID",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="客户",
            ),
        ),
        migrations.AddField(
            model_name="shopproduct",
            name="product_id",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="产品ID",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="product.product",
                verbose_name="商品",
            ),
        ),
        migrations.AddField(
            model_name="shopproduct",
            name="shop_id",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="店铺ID",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="account.shop",
                verbose_name="店铺",
            ),
        ),
    ]
