# Generated by Django 4.2.7 on 2023-11-16 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0009_remove_shop_account_remove_shopproduct_account_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shop",
            old_name="account_id",
            new_name="account",
        ),
        migrations.RenameField(
            model_name="shopproduct",
            old_name="account_id",
            new_name="account",
        ),
        migrations.RenameField(
            model_name="shopproduct",
            old_name="product_id",
            new_name="product",
        ),
        migrations.RemoveField(
            model_name="shopproduct",
            name="shop_id",
        ),
        migrations.AddField(
            model_name="shopproduct",
            name="shop",
            field=models.ForeignKey(
                default=1,
                help_text="店铺ID",
                on_delete=django.db.models.deletion.CASCADE,
                to="account.shop",
                verbose_name="店铺",
            ),
            preserve_default=False,
        ),
    ]
