# Generated by Django 4.2.7 on 2023-11-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0010_rename_account_id_shop_account_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default=None,
                help_text="客户头像",
                null=True,
                upload_to="static/account/avatar/images/%Y-%m-%d",
                verbose_name="头像",
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="image",
            field=models.ImageField(
                help_text="店铺的封面",
                upload_to="static/account/shop/images/%Y-%m-%d",
                verbose_name="图片地址",
            ),
        ),
    ]
