# Generated by Django 4.2.7 on 2023-11-24 14:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0012_alter_account_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shop",
            name="score",
            field=models.SmallIntegerField(
                default=1,
                help_text="店铺星级",
                validators=[
                    django.core.validators.MaxValueValidator(5),
                    django.core.validators.MinValueValidator(1),
                ],
                verbose_name="星级",
            ),
        ),
    ]
