# Generated by Django 4.2.7 on 2023-11-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="优惠券金额",
                        max_digits=10,
                        verbose_name="优惠券金额",
                    ),
                ),
                ("valve", models.IntegerField(help_text="门槛,0为无门槛", verbose_name="门槛")),
                (
                    "start_time",
                    models.BigIntegerField(
                        help_text="有效开始时间(时间戳)", verbose_name="有效开始时间"
                    ),
                ),
                (
                    "end_time",
                    models.BigIntegerField(
                        help_text="有效结束时间(时间戳)", verbose_name="有效结束时间"
                    ),
                ),
                ("count", models.IntegerField(help_text="库存", verbose_name="库存")),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(0, "官方优惠券"), (1, "店铺优惠券")],
                        help_text="优惠券类型",
                        verbose_name="优惠券类型",
                    ),
                ),
            ],
        ),
    ]
