# Generated by Django 4.2.6 on 2023-11-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0003_remove_product_image_productimg_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="ThreeType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.RenameModel(
            old_name="TypeClassify",
            new_name="OneType",
        ),
    ]
