# Generated by Django 4.2.7 on 2023-11-12 14:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0004_threetype_rename_typeclassify_onetype"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OneType",
        ),
        migrations.DeleteModel(
            name="ThreeType",
        ),
    ]
