# Generated by Django 4.2.7 on 2023-11-13 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0005_delete_onetype_delete_threetype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="cover",
            field=models.ImageField(
                help_text="产品封面", upload_to="static/product/images", verbose_name="图片封面"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="type",
            field=models.ForeignKey(
                help_text="产品分类ID",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="type_id",
                to="product.type",
            ),
        ),
        migrations.AlterField(
            model_name="productimg",
            name="img_type",
            field=models.SmallIntegerField(
                choices=[(0, "商品轮播"), (1, "商品详情")],
                help_text="图片类型(0:商品轮播,1:商品详情",
                verbose_name="图片类型",
            ),
        ),
        migrations.AlterField(
            model_name="productimg",
            name="img_url",
            field=models.ImageField(
                help_text="产品图片", upload_to="static/product/images", verbose_name="图片地址"
            ),
        ),
        migrations.AlterField(
            model_name="productimg",
            name="product",
            field=models.ForeignKey(
                help_text="商品ID",
                on_delete=django.db.models.deletion.CASCADE,
                to="product.product",
                verbose_name="商品",
            ),
        ),
        migrations.AlterField(
            model_name="type",
            name="className",
            field=models.CharField(
                help_text="产品分类名字", max_length=10, verbose_name="产品分类"
            ),
        ),
    ]
