# Generated by Django 4.2.7 on 2023-11-14 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0006_alter_product_cover_alter_product_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(default=1, help_text="产品描述", verbose_name="产品描述"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="cover",
            field=models.ImageField(
                help_text="产品封面", upload_to="static/product/images", verbose_name="产品封面"
            ),
        ),
        migrations.AlterField(
            model_name="productimg",
            name="img_type",
            field=models.SmallIntegerField(
                choices=[(0, "产品轮播"), (1, "产品详情")],
                help_text="图片类型(0:产品轮播,1:产品详情",
                verbose_name="图片类型",
            ),
        ),
        migrations.AlterField(
            model_name="productimg",
            name="product",
            field=models.ForeignKey(
                help_text="产品ID",
                on_delete=django.db.models.deletion.CASCADE,
                to="product.product",
                verbose_name="产品",
            ),
        ),
        migrations.CreateModel(
            name="ProductPropertyGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group",
                    models.CharField(
                        help_text="产品规格组合", max_length=225, verbose_name="产品规格组合"
                    ),
                ),
                (
                    "group_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="组合价格",
                        max_digits=10,
                        verbose_name="组合价格",
                    ),
                ),
                (
                    "group_sales",
                    models.IntegerField(
                        default=0, help_text="组合销售量", verbose_name="组合销售量"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="产品ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.product",
                        verbose_name="产品",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductProperty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "property",
                    models.CharField(
                        help_text="规格详情", max_length=225, verbose_name="规格详情"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="产品ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.product",
                        verbose_name="产品",
                    ),
                ),
            ],
        ),
    ]
