# Generated by Django 4.2.7 on 2023-11-14 12:45

from django.db import migrations, models
import utils.utils


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0007_product_description_alter_product_cover_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimg",
            name="img_url",
            field=models.ImageField(
                help_text="产品图片",
                upload_to=utils.utils.generate_image_path,
                verbose_name="图片地址",
            ),
        ),
    ]
