# Generated by Django 4.2.7 on 2023-11-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0008_alter_productimg_img_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimg",
            name="img_url",
            field=models.ImageField(
                help_text="产品图片",
                upload_to="static/product/1699966181===aed3e868-8521-41a3-8103-cb22f91593ec.jpg",
                verbose_name="图片地址",
            ),
        ),
    ]
