# Generated by Django 4.2.7 on 2023-11-15 04:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0011_rename_img_url_productimg_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="productproperty",
            name="property_name",
            field=models.CharField(
                default=1, help_text="规格名字", max_length=225, verbose_name="规格名字"
            ),
            preserve_default=False,
        ),
    ]
