# Generated by Django 4.2.7 on 2023-11-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0012_productproperty_property_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="productpropertygroup",
            name="group_image",
            field=models.ImageField(
                default=1,
                help_text="该组合的图片",
                upload_to="static/product/images",
                verbose_name="组合图片",
            ),
            preserve_default=False,
        ),
    ]
