# Generated by Django 4.2.7 on 2023-11-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0014_rename_productproperty_productspec_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="cover",
            field=models.ImageField(
                help_text="产品封面",
                upload_to="static/product/cover/images",
                verbose_name="产品封面",
            ),
        ),
        migrations.AlterField(
            model_name="productspecgroup",
            name="group_image",
            field=models.ImageField(
                help_text="该组合的图片",
                upload_to="static/product/spec/images",
                verbose_name="组合图片",
            ),
        ),
    ]
