# Generated by Django 4.2.7 on 2023-11-16 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0015_alter_product_cover_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="type",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="产品分类ID",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="type_id",
                to="product.type",
            ),
        ),
        migrations.AlterField(
            model_name="productimg",
            name="product",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="产品ID",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="product.product",
                verbose_name="产品",
            ),
        ),
        migrations.AlterField(
            model_name="productspec",
            name="product",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="产品ID",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="product.product",
                verbose_name="产品",
            ),
        ),
        migrations.AlterField(
            model_name="productspecgroup",
            name="product",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="产品ID",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="product.product",
                verbose_name="产品",
            ),
        ),
    ]
