# Generated by Django 4.2.7 on 2023-11-18 09:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0016_alter_product_type_alter_productimg_product_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productspecgroup",
            name="group_image",
            field=models.ImageField(
                blank=True,
                default=None,
                help_text="该组合的图片",
                null=True,
                upload_to="static/product/spec/images",
                verbose_name="组合图片",
            ),
        ),
    ]
