# Generated by Django 4.2.7 on 2023-11-20 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0019_type_image_alter_product_cover"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="一级分类名字", max_length=225, verbose_name="一级分类名字"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default=None,
                        help_text="一级分类图片",
                        null=True,
                        upload_to="static/product/Category1/images/%Y-%m-%d",
                        verbose_name="一级分类图片",
                    ),
                ),
                (
                    "sort",
                    models.IntegerField(default=1, help_text="排序", verbose_name="排序"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="check_status",
            field=models.SmallIntegerField(
                choices=[(0, "未审核"), (1, "已审核")],
                default=0,
                help_text="审核状态(0, '未审核'), (1, '已审核')",
                verbose_name="审核状态(0, '未审核'), (1, '已审核')",
            ),
        ),
        migrations.AddField(
            model_name="productspecgroup",
            name="count",
            field=models.IntegerField(default=1, help_text="组合库存", verbose_name="组合库存"),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Category2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="二级分类名字", max_length=225, verbose_name="二级分类名字"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default=None,
                        help_text="二级分类图片",
                        null=True,
                        upload_to="static/product/Category2/images/%Y-%m-%d",
                        verbose_name="二级分类图片",
                    ),
                ),
                (
                    "sort",
                    models.IntegerField(default=1, help_text="排序", verbose_name="排序"),
                ),
                (
                    "category1",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        help_text="一级分类ID",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.category1",
                        verbose_name="一级分类ID",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="category1",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="一级分类ID",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="product.category1",
                verbose_name="一级分类ID",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="category2",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="二级分类ID",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="product.category2",
                verbose_name="二级分类ID",
            ),
        ),
    ]
