# Generated by Django 4.2.7 on 2023-11-13 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0006_alter_product_cover_alter_product_type_and_more"),
        ("index", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indexcarousel",
            name="product",
            field=models.ForeignKey(
                help_text="产品ID",
                on_delete=django.db.models.deletion.CASCADE,
                to="product.product",
                verbose_name="轮播图产品",
            ),
        ),
        migrations.AlterField(
            model_name="indexseckill",
            name="product",
            field=models.ForeignKey(
                help_text="产品ID",
                on_delete=django.db.models.deletion.CASCADE,
                to="product.product",
                verbose_name="秒杀区产品",
            ),
        ),
        migrations.AlterField(
            model_name="indexsuggest",
            name="product",
            field=models.ForeignKey(
                help_text="产品ID",
                on_delete=django.db.models.deletion.CASCADE,
                to="product.product",
                verbose_name="首页推荐产品",
            ),
        ),
    ]
