# Generated by Django 4.2.7 on 2023-11-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("index", "0002_alter_indexcarousel_product_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indexcarousel",
            name="image",
            field=models.ImageField(upload_to="static/index/images/%Y-%m-%d"),
        ),
    ]
