# Generated by Django 4.2.6 on 2023-11-08 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("User", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProductCart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.IntegerField(help_text="购买数量", verbose_name="购买数量")),
                (
                    "user",
                    models.ForeignKey(
                        help_text="用户ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="User.wxuser",
                        verbose_name="用户",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[
                            (1, "等待付款"),
                            (2, "等待发货"),
                            (3, "运输中"),
                            (4, "已签收"),
                            (5, "已取消"),
                        ],
                        default=1,
                        help_text="订单状态",
                        verbose_name="订单状态",
                    ),
                ),
                (
                    "order_time",
                    models.BigIntegerField(help_text="下单时间", verbose_name="下单时间"),
                ),
                (
                    "pay_time",
                    models.BigIntegerField(help_text="支付时间", verbose_name="支付时间"),
                ),
                (
                    "deliver_time",
                    models.BigIntegerField(help_text="发货时间", verbose_name="发货时间"),
                ),
                (
                    "received_time",
                    models.BigIntegerField(help_text="签收时间", verbose_name="签收时间"),
                ),
                (
                    "postage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        help_text="运费",
                        max_digits=10,
                        null=True,
                        verbose_name="运费",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="用户ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="User.wxuser",
                        verbose_name="用户",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "receiver",
                    models.CharField(
                        help_text="收件人姓名", max_length=32, verbose_name="收件人姓名"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        help_text="收货地址", max_length=225, verbose_name="收货地址"
                    ),
                ),
                (
                    "cellphone",
                    models.CharField(
                        help_text="收件人手机号", max_length=11, verbose_name="收件人手机号"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, help_text="是否默认地址", verbose_name="是否默认地址"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="创建时间",
                        null=True,
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="用户ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="User.wxuser",
                        verbose_name="用户",
                    ),
                ),
            ],
        ),
    ]
