# Generated by Django 4.2.6 on 2023-11-09 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0004_threetype_rename_typeclassify_onetype"),
        ("User", "0002_userproductcart_userorder_useraddress"),
    ]

    operations = [
        migrations.AddField(
            model_name="userorder",
            name="product",
            field=models.ForeignKey(
                default=1,
                help_text="商品ID",
                on_delete=django.db.models.deletion.CASCADE,
                to="product.product",
                verbose_name="商品",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userproductcart",
            name="product",
            field=models.ForeignKey(
                default=1,
                help_text="商品ID",
                on_delete=django.db.models.deletion.CASCADE,
                to="product.product",
                verbose_name="商品",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="wxuser",
            name="avatar",
            field=models.FileField(upload_to="static/User/images", verbose_name="微信头像"),
        ),
    ]
