# Generated by Django 4.2.6 on 2023-11-09 10:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("User", "0004_userorder_order_number_alter_userorder_deliver_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wxuser",
            name="avatar",
            field=models.ImageField(
                help_text="用户头像", upload_to="static/User/images", verbose_name="微信头像"
            ),
        ),
        migrations.AlterField(
            model_name="wxuser",
            name="openId",
            field=models.CharField(
                help_text="openId", max_length=100, verbose_name="openId"
            ),
        ),
        migrations.AlterField(
            model_name="wxuser",
            name="username",
            field=models.CharField(
                help_text="微信用户名字", max_length=225, verbose_name="用户名"
            ),
        ),
    ]
