# Generated by Django 4.2.7 on 2023-11-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("User", "0005_alter_wxuser_avatar_alter_wxuser_openid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userorder",
            name="status",
            field=models.SmallIntegerField(
                choices=[(1, "等待付款"), (2, "等待发货"), (3, "运输中"), (4, "已签收"), (5, "已取消")],
                default=1,
                help_text="订单状态(1, '等待付款'), (2, '等待发货'), (3, '运输中'), (4, '已签收'), (5, '已取消')",
                verbose_name="订单状态",
            ),
        ),
    ]
