# Generated by Django 4.2.7 on 2023-11-16 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0016_alter_product_type_alter_productimg_product_and_more"),
        ("User", "0006_alter_userorder_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraddress",
            name="user",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="用户ID",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="User.wxuser",
                verbose_name="用户",
            ),
        ),
        migrations.AlterField(
            model_name="userorder",
            name="product",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="商品ID",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="product.product",
                verbose_name="商品",
            ),
        ),
        migrations.AlterField(
            model_name="userorder",
            name="user",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="用户ID",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="User.wxuser",
                verbose_name="用户",
            ),
        ),
        migrations.AlterField(
            model_name="userproductcart",
            name="product",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="商品ID",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="product.product",
                verbose_name="商品",
            ),
        ),
        migrations.AlterField(
            model_name="userproductcart",
            name="user",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="用户ID",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="User.wxuser",
                verbose_name="用户",
            ),
        ),
    ]
