# Generated by Django 4.2.7 on 2023-11-16 11:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("User", "0008_userproductcart_spec"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userproductcart",
            old_name="spec",
            new_name="product_spec_group",
        ),
    ]
