# Generated by Django 4.2.7 on 2023-11-16 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0016_alter_product_type_alter_productimg_product_and_more"),
        ("User", "0009_rename_spec_userproductcart_product_spec_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userproductcart",
            name="product_spec_group",
            field=models.ForeignKey(
                default=1,
                help_text="商品规格ID",
                on_delete=django.db.models.deletion.CASCADE,
                to="product.productspecgroup",
                verbose_name="规格",
            ),
            preserve_default=False,
        ),
    ]
