# Generated by Django 4.2.7 on 2023-11-16 11:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("User", "0010_alter_userproductcart_product_spec_group"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userproductcart",
            old_name="product_spec_group",
            new_name="spec",
        ),
    ]
