# Generated by Django 4.2.7 on 2023-11-16 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0016_alter_product_type_alter_productimg_product_and_more"),
        ("User", "0011_rename_product_spec_group_userproductcart_spec"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userproductcart",
            name="spec",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="商品规格ID",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="product.productspecgroup",
                verbose_name="规格",
            ),
        ),
    ]
