# Generated by Django 4.2.7 on 2023-11-20 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0012_alter_userproductcart_spec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wxuser',
            name='avatar',
            field=models.ImageField(help_text='用户头像', upload_to='static/User/images/%Y-%m-%d', verbose_name='微信头像'),
        ),
    ]
