# Generated by Django 4.2.7 on 2023-11-20 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("User", "0013_alter_wxuser_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="userorder",
            name="address",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="地址ID",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="User.useraddress",
                verbose_name="订单地址",
            ),
        ),
    ]
