# Generated by Django 4.2.7 on 2023-11-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("User", "0014_userorder_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wxuser",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default=None,
                help_text="用户头像",
                null=True,
                upload_to="static/User/images/%Y-%m-%d",
                verbose_name="微信头像",
            ),
        ),
    ]
