# Generated by Django 4.2.7 on 2023-11-26 13:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("User", "0016_userproductcart_is_select_userasset"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userproductcart",
            name="product",
        ),
    ]
