# Generated by Django 4.2.7 on 2023-11-28 01:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("User", "0018_userorder_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userorder",
            name="count",
            field=models.IntegerField(
                blank=True, default=0, help_text="购买数量", null=True, verbose_name="购买数量"
            ),
        ),
    ]
