# Generated by Django 4.2.7 on 2023-11-28 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("User", "0019_alter_userorder_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="userorder",
            name="money",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                help_text="金额",
                max_digits=10,
                null=True,
                verbose_name="金额",
            ),
        ),
    ]
