# Generated by Django 4.2.7 on 2023-11-29 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0023_product_sold"),
        ("User", "0021_userorder_date_wxuser_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="AfterSale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "application_time",
                    models.DateTimeField(
                        auto_now_add=True, help_text="申请售后时间", null=True
                    ),
                ),
                (
                    "money",
                    models.DecimalField(
                        decimal_places=2, default=0, help_text="金额", max_digits=10
                    ),
                ),
                (
                    "processing_time",
                    models.DateTimeField(
                        blank=True, default=None, help_text="处理时间", null=True
                    ),
                ),
                (
                    "after_sale_status",
                    models.SmallIntegerField(
                        choices=[(0, "待处理"), (1, "处理中"), (2, "已处理")],
                        default=0,
                        help_text="申请状态",
                    ),
                ),
                (
                    "cause",
                    models.TextField(
                        help_text="申请售后原因((0, '待处理'), (1, '处理中'), (2, '已处理'))"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        help_text="申请售后商品ID",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        help_text="用户",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="User.wxuser",
                    ),
                ),
            ],
        ),
    ]
