# Generated by Django 4.2.7 on 2023-11-13 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("User", "0005_alter_wxuser_avatar_alter_wxuser_openid_and_more"),
        ("product", "0005_delete_onetype_delete_threetype"),
        ("comment", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="upvote",
        ),
        migrations.AlterField(
            model_name="comment",
            name="product",
            field=models.ForeignKey(
                help_text="产品ID",
                on_delete=django.db.models.deletion.CASCADE,
                to="product.product",
                verbose_name="产品",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="user",
            field=models.ForeignKey(
                help_text="用户ID",
                on_delete=django.db.models.deletion.CASCADE,
                to="User.wxuser",
                verbose_name="评论产品",
            ),
        ),
        migrations.AlterField(
            model_name="commentimage",
            name="comment",
            field=models.ForeignKey(
                help_text="评论ID(哪个评论的图片)",
                on_delete=django.db.models.deletion.CASCADE,
                to="comment.comment",
                verbose_name="评论",
            ),
        ),
        migrations.AlterField(
            model_name="commentimage",
            name="image",
            field=models.ImageField(
                help_text="评论图片", upload_to="static/comment/images"
            ),
        ),
        migrations.AlterField(
            model_name="commentupvote",
            name="comment",
            field=models.ForeignKey(
                help_text="评论ID(哪个评论的数量)",
                on_delete=django.db.models.deletion.CASCADE,
                to="comment.comment",
                verbose_name="产品",
            ),
        ),
        migrations.AlterField(
            model_name="commentupvote",
            name="count",
            field=models.IntegerField(
                default=0, help_text="评论的点赞数", verbose_name="评论的点赞数量"
            ),
        ),
        migrations.AlterField(
            model_name="commentupvote",
            name="user",
            field=models.ForeignKey(
                help_text="用户ID",
                on_delete=django.db.models.deletion.CASCADE,
                to="User.wxuser",
                verbose_name="点赞用户",
            ),
        ),
    ]
