# Generated by Django 4.2.7 on 2023-11-16 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0016_alter_product_type_alter_productimg_product_and_more"),
        ("User", "0007_alter_useraddress_user_alter_userorder_product_and_more"),
        ("comment", "0002_remove_comment_upvote_alter_comment_product_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="product",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="产品ID",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="product.product",
                verbose_name="产品",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="user",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="用户ID",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="User.wxuser",
                verbose_name="评论产品",
            ),
        ),
        migrations.AlterField(
            model_name="commentimage",
            name="comment",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="评论ID(哪个评论的图片)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="comment.comment",
                verbose_name="评论",
            ),
        ),
        migrations.AlterField(
            model_name="commentupvote",
            name="comment",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="评论ID(哪个评论的数量)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="comment.comment",
                verbose_name="产品",
            ),
        ),
        migrations.AlterField(
            model_name="commentupvote",
            name="user",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="用户ID",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="User.wxuser",
                verbose_name="点赞用户",
            ),
        ),
    ]
