# Generated by Django 4.2.7 on 2023-11-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comment", "0003_alter_comment_product_alter_comment_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commentimage",
            name="image",
            field=models.ImageField(
                help_text="评论图片", upload_to="static/comment/images/%Y-%m-%d"
            ),
        ),
    ]
